# Generated by Django 5.2.8 on 2025-11-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/img/default/default01.jpg', null=True, upload_to='products/'),
        ),
    ]
