# Generated by Django 5.2.8 on 2026-01-23 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_description_alter_category_name_and_more'),
        ('products', '0007_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoría', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='category.category'),
        ),
    ]
